### ISSUE TITLE
Scrollbar not intuitive on desktop browsers

### ISSUE THREAD

**Issue by wimpie3** [triceam/app-UI#16]
To scroll a page on desktop browsers, users have to use the "click and pull down" movement with their mouse. Furthermore, clicking and pulling activates the link underneath the mouse.

Perhaps a detection system should be put in place to disable mobile scrolling on a desktop pc?

**Comment by triceam** [comment]
iScroll now only enabled if touch is supported, otherwise uses default browser scrolling
