### ISSUE TITLE
display loading indicator while rendering a page

### ISSUE THREAD

**Issue by sonaba** [triceam/app-UI#35]
How can i display the loading indicator while im rendering a page? i get the page content from rss feed so it can take a while.

**Comment by sonaba** [comment]
sry. i have it. sorry for disturbing. btw this is a great library, i hope you will keep it updated in the future as well.

**Comment by Onslot** [comment]
@sonaba what was your solution if you do not mind sharing?

**Comment by triceam** [comment]
Look at my Census browser example (the renderContent function). https://github.com/triceam/US-Census-Browser/blob/master/client/js/application.js 
Just have HTML with a loading animation, swap it out with HTML once content is loaded.  You will have to refresh the scroller once your new content is loaded.

**Comment by Onslot** [comment]
Hi Andrew,

Thank you again for your response. What i am trying to accomplish is a
login page so after the user logs in goes to a homepage, this is my first
phonegap or mobile app so I am experimenting. I was wondering if you have a
sample app or point me to the right direction how to accomplish a clean log
in keeping user logged in until  timeout like chase app or amex app? Can
this be done with phonegap? I was looking at using localstorage html 5? Can
this be done with the app-ui?

Thanks,
Mark

**Comment by triceam** [comment]
You could use local storage, or just use a session cookie.  Once the cookie expires, force another login.  Here's a sample from Ray Camden (fellow Adobe Evangelist) showing how to do a login in a jQuery mobile/PhoneGap app: http://www.raymondcamden.com/index.cfm/2011/11/10/Example-of-serverbased-login-with-PhoneGap

**Comment by Onslot** [comment]
Hi Andrew,

If you do not mind, in Phonegap the html radio buttons a quiet small, is
there anyway to make them a bit bigger, what happens is i have a multiple
choice selection and they are radio buttons but sometimes they do not get
selected, i have to tap it a few times sometimes.

Thanks,
Mark
