### ISSUE TITLE
ViewNavigation Issue With Jelly Bean.

### ISSUE THREAD

**Issue by rkumar670** [triceam/app-UI#40]
@triceam 
Thanks for these wonderful framework
working perfectly in iphone 4 and android lower version like 2.3

I did some changes in the ViewNavigator.js files according to me for header and footer.

I app is working fine in lower version of android version but not working in jelly bean.

when i click on the list item it automatically push the other method  views then white screen will appears.

Thanks in advance. Please reply asap urgent.

**Comment by bugwelle** [comment]
I think what you mean is an Android bug. Let's say that the HTML(5) support isn't that good. I read an article about jQueryMobile where this problem was described (can't find it now). But it could also be a bug in your code (ViewNavigator) where the transition may not be handled correctly. :P

**Comment by rkumar670** [comment]
but the same app is working perfectly in lowest version of android

**Comment by triceam** [comment]
Can you elaborate on this some more?  What did you change, and what are the symptoms of the bug?  Are there any error messages? I have apps using the ViewNavigator which work fine on Android 2.3 - through 4.2 (the latest)

**Comment by rkumar670** [comment]
i check the log in eclipse i saw the event is firing twice . i don't now why it is happening.

**Comment by triceam** [comment]
that is an android-specific issue with touch events

**Comment by rkumar670** [comment]
![Screenshot_2013-02-17-08-36-00 jpg](https://f.cloud.github.com/assets/1597317/181267/fc22b5fe-7c49-11e2-8a32-41f935fb4875.png)
may you tell me how to solve this issue
i attach a screenshot the problem is  the back button not visible some time i have touch the screen then it visible.
i am closing this thread now . if you can tell me any suggestion to sort out this problem or tell us what is the proper way to use the viewnavigator js to develop the hybrid app. i m currently using the simple methods..if u have a suggestion most welcome... i also like your blogs post. thanks for sharing...:)
