### ISSUE TITLE
iOS Styled Back Buttons

### ISSUE THREAD

**Issue by triceam** [triceam/app-UI#7]
make them possible, with the left-side point like an arrow.

**Comment by rkumar670** [comment]
yes i already did that with left right button same like ios and also with footer...

**Comment by bugwelle** [comment]
I'd prefer to style that buttons and everything else on my own. :)
There are several app-ui's like (ratchet)[http://maker.github.com/ratchet/] and I want to use APP-UI only as a javascript 'wrapper' (caching, changing views, ...).

**Comment by triceam** [comment]
These can be easily changed by just adding css styles.  I think this one isn't necessary... closing it.
